import 'dart:typed_data';

import 'package:sonicdb/annotation.dart';

part 'App.g.dart';

@Entity(name: "apps")
abstract class App {
  @PrimaryKey(autoGenerated: true)
  @ColumnInfo(name: "_id")
  int id = 0;
  @ColumnInfo(name: "package_name")
  late String packageName = "";
  @ColumnInfo(name: "name")
  late String appName = "";
  @ColumnInfo(name: "day_volume")
  int dayVolume = 0;
  @ColumnInfo(name: "night_volume")
  int nightVolume = 0;
  @ColumnInfo(name: "day_brightness")
  int dayBrightness = 0;
  @ColumnInfo(name: "night_brightness")
  int nightBrightness = 0;
  @ColumnInfo(name: "icon")
  late Uint8List icon;

  factory App({Map? value}) = _App;

  Map toMap();
}
