// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'AppDatabase.dart';

// **************************************************************************
// DatabasePartGenerator
// **************************************************************************

class _AppDatabase extends SonicDb implements AppDatabase {
  _AppDatabase({
    String name = "sonicdb",
    Map<String, dynamic> entities = const {},
    int version = 1,
    bool useDeviceProtectedStorage = false,
  }) : super(
            name: name,
            entities: entities,
            version: version,
            useDeviceProtectedStorage: useDeviceProtectedStorage) {
    apps = AppCollection(this);
    var entityApp = Map();
    entityApp['name'] = 'apps';
    entityApp['fields'] = Map();
    var entityApp_id = Map();
    entityApp_id['primaryKey'] = true;
    entityApp_id['autoGenerated'] = true;
    entityApp_id['name'] = '_id';
    entityApp_id['type'] = 'integer';
    entityApp_id['notNull'] = true;
    entityApp['fields']['id'] = entityApp_id;
    var entityApp_packageName = Map();
    entityApp_packageName['name'] = 'package_name';
    entityApp_packageName['type'] = 'text';
    entityApp_packageName['notNull'] = true;
    entityApp['fields']['packageName'] = entityApp_packageName;
    var entityApp_appName = Map();
    entityApp_appName['name'] = 'name';
    entityApp_appName['type'] = 'text';
    entityApp_appName['notNull'] = true;
    entityApp['fields']['appName'] = entityApp_appName;
    var entityApp_dayVolume = Map();
    entityApp_dayVolume['name'] = 'day_volume';
    entityApp_dayVolume['type'] = 'integer';
    entityApp_dayVolume['notNull'] = true;
    entityApp['fields']['dayVolume'] = entityApp_dayVolume;
    var entityApp_nightVolume = Map();
    entityApp_nightVolume['name'] = 'night_volume';
    entityApp_nightVolume['type'] = 'integer';
    entityApp_nightVolume['notNull'] = true;
    entityApp['fields']['nightVolume'] = entityApp_nightVolume;
    var entityApp_dayBrightness = Map();
    entityApp_dayBrightness['name'] = 'day_brightness';
    entityApp_dayBrightness['type'] = 'integer';
    entityApp_dayBrightness['notNull'] = true;
    entityApp['fields']['dayBrightness'] = entityApp_dayBrightness;
    var entityApp_nightBrightness = Map();
    entityApp_nightBrightness['name'] = 'night_brightness';
    entityApp_nightBrightness['type'] = 'integer';
    entityApp_nightBrightness['notNull'] = true;
    entityApp['fields']['nightBrightness'] = entityApp_nightBrightness;
    var entityApp_icon = Map();
    entityApp_icon['name'] = 'icon';
    entityApp_icon['type'] = 'blob';
    entityApp_icon['notNull'] = true;
    entityApp['fields']['icon'] = entityApp_icon;
    _entities['App'] = entityApp;
  }

  static String _name = 'varity.db';

  static Map<String, dynamic> _entities = Map<String, dynamic>();

  static int _version = 2;

  static bool _useDeviceProtectedStorage = true;

  static AppDatabase? _instance;

  late AppCollection apps;

  static AppDatabase getInstance() {
    if (_instance != null) {
      return _instance!;
    } else {
      _instance = _AppDatabase(
          name: _name,
          entities: _entities,
          version: _version,
          useDeviceProtectedStorage: _useDeviceProtectedStorage);
      return _instance!;
    }
  }

  @override
  void onUpgrade() {
    log("on database upgraded");
  }

  @override
  void onCreate() {
    log("on database created");
  }
}
