name: Varity Workflow

on: [push, workflow_dispatch]
jobs:
  build:
    
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.9'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get
      
      - name: Setup key.properties
        run: cd android; cat key.properties; cd ..
          # cd android;
          # echo storeFile=\"$ANDROID_STORE_FILE\" > key.properties;
          # echo storePassword=\"$ANDROID_STORE_PASSWORD\" > key.properties;
          # echo keyAlias=\"$ANDROID_KEY_ALIAS\" > key.properties;
          # echo keyPassword=\"$ANDROID_KEY_PASSWORD\" > key.properties;

      # let's exlude the tests right now, didn't have the time to make all this tests
      # - name: Run unit tests
      #   run: flutter test --coverage

      # - name: Upload to code coverage
      #   uses: codecov/codecov-action@v1.2.2
      #   with:
      #     token: ${{secrets.CODECOV_TOKEN}}
      #     file: coverage/lcov.info

      # - name: Run integration tests
      #   uses: reactivecircus/android-emulator-runner@v1
      #   with:
      #     api-level: 33
      #     script: flutter test integration_test
      - name: Build APK
        env:
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          ANDROID_STORE_PASSWORD: ${{ secrets.ANDROID_STORE_PASSWORD }}
          ANDROID_STORE_FILE: ${{ secrets.ANDROID_STORE_FILE }}
        run: flutter build apk
      
      - name: Build Appbundle
        env:
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          ANDROID_STORE_PASSWORD: ${{ secrets.ANDROID_STORE_PASSWORD }}
          ANDROID_STORE_FILE: ${{ secrets.ANDROID_STORE_FILE }}
        run: flutter build appbundle

      - name: Upload APK
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tags: false
          draft: true
          overwrite: true
          file: build/app/outputs/apk/release/app-release.apk

      - name: Upload appbundle
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tags: false
          draft: true
          overwrite: true
          file: build/app/outputs/bundle/release/app-release.aab
