on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
name: Varity Workflow
jobs:
  prerelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.9'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get
      

      # let's exlude the tests right now, don't have the time to make all these tests
      # - name: Run unit tests
      #   run: flutter test --coverage

      # - name: Upload to code coverage
      #   uses: codecov/codecov-action@v1.2.2
      #   with:
      #     token: ${{secrets.CODECOV_TOKEN}}
      #     file: coverage/lcov.info

      # - name: Run integration tests
      #   uses: reactivecircus/android-emulator-runner@v1
      #   with:
      #     api-level: 33
      #     script: flutter test integration_test
      - name: Build APK
        run: flutter build apk
      
      - name: Build Appbundle
        run: flutter build appbundle
      
      - name: "find env"
        run: |
          set | grep GITHUB_ | grep -v GITHUB_TOKEN
          zip -r pkg.zip *.md
          echo "$(openssl rand -hex 6)" > "random-name-$(openssl rand -hex 6).txt"
          echo "$(openssl rand -hex 6)" > "random-name-$(openssl rand -hex 6).txt"
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}-prelease
          release_name: Release ${{ github.ref }} (prelease)
          draft: false
          prerelease: true

      - name: Upload APK & Appbundle
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          overwrite: true
          verbose: true
          file: build/app/outputs/apk/release/app-release.apk;build/app/outputs/bundle/release/app-release.aab
          release_id: ${{ steps.create_release.outputs.id }}
          

